### ISSUE TITLE
The tutorial and files works for US, EU and JP WiiU units?

### ISSUE THREAD

**Issue by equisgroup** [Mithrenes/WiiUGuide#3]
I haven't checked the files but read the readme.md and there there is nothing about console region and file compatibility.

Can anyone confirm?

**Comment by ItsKipz** [comment]
Not sure about jpn units, but EU should be fine

**Comment by equisgroup** [comment]
Thanks. My wiiu is US. Will check online about the files and if any needs to be region specific before try.

**Comment by Mithrenes** [comment]
All files here work for any console. Only games are region locked (and there is already a guide for making your console region free).

**Comment by equisgroup** [comment]
Thanks. Once at home going to read, try it.
